name: Update Kubernetes Manifest

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      service:
        description: 'The name of the container image to use'
        required: true
        default: 'hpa-example'
      image:
        description: 'The name of the container image to use'
        required: true
        default: 'registry.k8s.io/hpa-example'
      tag:
        description: 'The tag of the container image'
        required: true
        default: 'latest'

jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update tag container image
        run: |
          #!/bin/sh

          set -e

          # --- 1. Validate Inputs ---
          IMAGE_NAME="${{ github.event.inputs.image }}"
          IMAGE_TAG="${{ github.event.inputs.tag }}"

          if [ -z "$IMAGE_NAME" ] || [ -z "$IMAGE_TAG" ]; then
            echo "::error::'image_name' and 'image_tag' inputs cannot be empty."
            exit 1
          fi

          # --- 2. Install yq ---
          curl -s -L https://github.com/mikefarah/yq/releases/download/v4.45.4/yq_linux_amd64.tar.gz | tar xzf -
          mv yq_linux_amd64 /usr/local/bin/yq

          # --- 3. Update Manifest ---
          IMAGE_FULL_NAME="$IMAGE_NAME:$IMAGE_TAG"
          TARGET_FILE="${{ github.event.inputs.service }}/deploy.yaml"

          yq -i ".spec.template.spec.containers[0].image = \"$IMAGE_FULL_NAME\"" "$TARGET_FILE"

          # --- 4. Verify Change ---
          echo "--- Verifying content of $TARGET_FILE ---"
          cat "$TARGET_FILE"
